### ISSUE TITLE
Data service team

### ISSUE THREAD

**Issue by trickvi** [openspending/next#10]
A team managing static (infrequently updated) data, e.g. COFOG, Consumer Price Index (for inflation calculations), GFSM etc. Provides the data as an API (for javascript calls) and as downloadable static files for local caching/use by software.

**Comment by tryggvib** [comment]
I'm in

**Comment by tryggvib** [comment]
(I'm guessing this is where you pitch new ideas for budget services)

**Comment by pwalsh** [comment]
This is an excellent idea, and is of course critical for moving forward with comparative analysis and other types of work that require additional context.

I think we should also try to define what is in scope for OpenSpending to provide, and what is not, especially as we'll want to provide support across multiple countries/regions/places.

WDYT? 

Also @idoivri mentioned some other contextual data points [here](https://discuss.okfn.org/t/sharing-spend-data-use-cases/270/5)

**Comment by idoivri** [comment]
I can lend a hand to such an effort.

**Comment by tryggvib** [comment]
What I had in mind is a service that's not solely tied to openspending, i.e. not a budget service per se, but something that can begin by being used by openspending. Similar to goodtables. Something like an automatic converter of datapackages to a RESTful API. It probably fits better in the frictionless data proejct, but this would be designed (from my end) with openspending as the use case.

**Comment by pwalsh** [comment]
@pudo has some stuff here: https://github.com/pudo/spendb/tree/master/spendb/reference/data which may or may not already be covered by existing data packages, eg: http://data.okfn.org/data/core/country-list

**Comment by pudo** [comment]
Ok, I'm now moving the spendb reference data out to https://github.com/pudo/fiscalmodel so that it can be more easily re-used. Just thought I'd drop a backref here.

**Comment by pwalsh** [comment]
Simplifying this. Just introduce yourself at https://discuss.okfn.org/c/openspending if you want to take part.

**Comment by pwalsh** [comment]
@pudo with regard to fiscal model, I think we should take a deep look at the codelists being prepared for ob.eu and leverage that work to see what we can integrate into fiscal model, as service, or lib, or both
