### ISSUE TITLE
Service Integration team

### ISSUE THREAD

**Issue by pwalsh** [openspending/next#6]
Register your interest in working on the task service team here. See the [Roadmap](http://labs.openspending.org/next/roadmap.html) for more information.

**Comment by pwalsh** [comment]
Hey @tryggvib remember Nameko? I just saw this writeup: http://lucumr.pocoo.org/2015/4/8/microservices-with-nameko/

**Comment by tryggvib** [comment]
"Task service" is not super clear to me. Could this be called "Service Integration team" or something like that. That's what I signed up for, i.e. how tasks move between services.

**Comment by pwalsh** [comment]
@tryggvib yes definitely, that is better terminology. I'll update.

**Comment by pwalsh** [comment]
Simplifying this. Just introduce yourself at https://discuss.okfn.org/c/openspending if you want to take part.
