### ISSUE TITLE
OpenSpending Data Package team

### ISSUE THREAD

**Issue by pwalsh** [openspending/next#7]
Register your interest in working on the OpenSpending Data Package team here. See the [Roadmap](http://labs.openspending.org/next/roadmap.html) for more information.

**Comment by rgrp** [comment]
I'm in.

**Comment by pwalsh** [comment]
I'm in too :)

**Comment by pwalsh** [comment]
Simplifying this. Just introduce yourself at https://discuss.okfn.org/c/openspending if you want to take part.
