### ISSUE TITLE
Data migration team

### ISSUE THREAD

**Issue by pwalsh** [openspending/next#8]
Register your interest in working on the data migration team here. See the [Roadmap](http://labs.openspending.org/next/roadmap.html) for more information.

**EDIT**: Work is in progress as noted below. 

The work tasks can be tracked [here on the development board](https://trello.com/c/19X8lvwk/1-migrate-existing-os-data-to-osdp), and an overview of the work required is here on the [OpenSpending Next site](http://community.openspending.org/next/08-data-migration/)

**Comment by pudo** [comment]
FWIW, [script to dump OS database into CSV flat files](https://github.com/mapthemoney/spendb/blob/master/contrib/os_export/export.py).

**Comment by tryggvib** [comment]
I'm starting work on this: http://community.openspending.org/next/08-data-migration/

Anyone can chip in and I'll have a look at @pudo's script

**Comment by rgrp** [comment]
@tryggvib awesome - my one suggestion is to not try and do everything but focus on one or two datasets and go round the loop on those first as we iron things out. I specifically recommend:

https://github.com/openspending/dpkg-cra

Which is already sort of data packaged and is our "classic" budget dataset (UK CRA)

**Comment by tryggvib** [comment]
@rgrp yes that's the plan, although I'll try to pick edge cases rather than straightforward ones, i.e. multiple authors, unsuccessful runs on sources etc.

UK CRA is one of those edge cases because in OpenSpending it has no sources and no team members. It just materialized out of thin air.

**Comment by tryggvib** [comment]
Yep I think we'll go for @pudo's script with a change that will also include team members in the ``dataset.json``

**Comment by pwalsh** [comment]
that's great. Thanks for the initial work @pudo

**Comment by tryggvib** [comment]
@rgrp These are the datasets I'll be trialling against:

* tekjur-rikissjods
* uppgjor-rikissjods
* tryggvis_test_dataset
* bosnia-herzegovina
* tunisia_budget
* bosnian_test
* save_dimensions
* ukgov-finances-cra

More details on how I picked them here: http://community.openspending.org/next/08-data-migration/

**Comment by rgrp** [comment]
Seems good. Note: I do not think we are supporting private datasets going forward. I think everything is auto-public so, at least at this point, I would not be supporting any private stuff.

**Comment by tryggvib** [comment]
@rgrp Yes I agree. We've been discussing private datasets a bit here: https://trello.com/c/19X8lvwk/1-migrate-existing-os-data-to-osdp

Dropping private datasets means we'll only use around 42% of the datasets that are in OpenSpending (don't know how many of the remaining datasets actually work) but it does make everything a lot simpler (we might lose some datasets that are "in progress" which would be unfortunate but there's no way around it).

**Comment by rgrp** [comment]
@tryggvib commented there (btw are we using here or trello for this discussion). As i noted in trello:

- I think there is no problem ignoring private datasets as these numbers are wildly skewed by the setup of OS. And anyway I don't think private datasets (by their nature) are that significant at this point.
- I certainly think ok at this point to focus on public datasets.
- I think we should go for a public dataset only approach in future (though the idea of a "published" flag may be useful in future - to separate out experiments from stuff that is "raedy to go" - but that is a separate topic ...)

**Comment by pwalsh** [comment]
Discussion should be in trello. This thread was just to let people register their interest.

**Comment by pwalsh** [comment]
Simplifying this. Just introduce yourself at https://discuss.okfn.org/c/openspending if you want to take part.
