### ISSUE TITLE
Tech Lead Group

### ISSUE THREAD

**Issue by pwalsh** [openspending/next#9]
If you would like to join the OpenSpending Tech Lead Group, let us know here. 

See the [Roadmap](http://labs.openspending.org/next/) for more information.

**Comment by pwalsh** [comment]
Me.

**Comment by tryggvib** [comment]
Doesn't this materialise from the other groups?

**Comment by pwalsh** [comment]
It could. Let's see. Possibly, some may be interested in this without "signing up" for a working team around particular services/components.

**Comment by rgrp** [comment]
I volunteer ...

**Comment by aivuk** [comment]
Me too.

**Comment by pwalsh** [comment]
Great to see you here @aivuk.

**Comment by tryggvib** [comment]
I'll sign up as well then

**Comment by pwalsh** [comment]
Simplifying this. Just introduce yourself at https://discuss.okfn.org/c/openspending if you want to take part.
